#pragma once
#include <QGraphicsScene>
#include <QGraphicsView>
#include <QGraphicsItem>
#include <QMediaPlayer>
#include <QPushButton>
#include <QVBoxLayout>
#include <QMainWindow>
#include <QKeyEvent>
#include <QGroupBox>
#include <QResource>
#include <QPainter>
#include <QPixmap>
#include <QObject>
#include <QWidget>
#include <QString>
#include <QDebug>
#include <QTimer>
#include <QSound>
#include <QLabel>
#include <QFile>
